/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as MarketplaceListingKeyRouteImport } from './routes/marketplace.$listingKey'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSessionsRouteImport } from './routes/dashboard.sessions'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardPoliciesRouteImport } from './routes/dashboard.policies'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMobileRouteImport } from './routes/dashboard.mobile'
import { Route as DashboardMarketplaceRouteImport } from './routes/dashboard.marketplace'
import { Route as DashboardDevicesRouteImport } from './routes/dashboard.devices'
import { Route as DashboardDeveloperRouteImport } from './routes/dashboard.developer'
import { Route as DashboardContactsRouteImport } from './routes/dashboard.contacts'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAutomationRouteImport } from './routes/dashboard.automation'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAutomationIndexRouteImport } from './routes/dashboard.automation.index'
import { Route as DashboardPoliciesRemoteInputRouteImport } from './routes/dashboard.policies.remote-input'
import { Route as DashboardPoliciesFileTransferRouteImport } from './routes/dashboard.policies.file-transfer'
import { Route as DashboardPoliciesClipboardRouteImport } from './routes/dashboard.policies.clipboard'
import { Route as DashboardDevicesDeviceIdRouteImport } from './routes/dashboard.devices.$deviceId'
import { Route as DashboardAutomationTasksRouteImport } from './routes/dashboard.automation.tasks'
import { Route as DashboardAutomationSettingsRouteImport } from './routes/dashboard.automation.settings'
import { Route as DashboardAutomationSchedulerRouteImport } from './routes/dashboard.automation.scheduler'
import { Route as DashboardAutomationRateLimitsRouteImport } from './routes/dashboard.automation.rate-limits'
import { Route as DashboardAutomationPipelinesRouteImport } from './routes/dashboard.automation.pipelines'
import { Route as DashboardAutomationLogsRouteImport } from './routes/dashboard.automation.logs'
import { Route as DashboardAutomationArtifactsRouteImport } from './routes/dashboard.automation.artifacts'
import { Route as DashboardAutomationAlertsRouteImport } from './routes/dashboard.automation.alerts'
import { Route as DashboardAutomationAccountsRouteImport } from './routes/dashboard.automation.accounts'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicV1SessionsRouteImport } from './routes/api/public/v1/sessions'
import { Route as ApiPublicV1NotificationsRouteImport } from './routes/api/public/v1/notifications'
import { Route as ApiPublicV1MeRouteImport } from './routes/api/public/v1/me'
import { Route as ApiPublicV1DevicesRouteImport } from './routes/api/public/v1/devices'
import { Route as ApiPublicV1WebhooksEndpointsRouteImport } from './routes/api/public/v1/webhooks.endpoints'
import { Route as ApiPublicV1SupportTicketsRouteImport } from './routes/api/public/v1/support.tickets'
import { Route as ApiPublicV1SessionsSessionIdRouteImport } from './routes/api/public/v1/sessions.$sessionId'
import { Route as ApiPublicV1DevicesDeviceIdRouteImport } from './routes/api/public/v1/devices.$deviceId'
import { Route as ApiPublicV1BillingUsageRouteImport } from './routes/api/public/v1/billing.usage'
import { Route as ApiPublicV1AutomationPipelinesRouteImport } from './routes/api/public/v1/automation.pipelines'
import { Route as ApiPublicV1AuditLogsRouteImport } from './routes/api/public/v1/audit.logs'
import { Route as ApiPublicV1WebhooksEndpointsEndpointIdRouteImport } from './routes/api/public/v1/webhooks.endpoints.$endpointId'
import { Route as ApiPublicV1SessionsSessionIdEndRouteImport } from './routes/api/public/v1/sessions.$sessionId.end'
import { Route as ApiPublicV1DevicesDeviceIdPresenceRouteImport } from './routes/api/public/v1/devices.$deviceId.presence'
import { Route as ApiPublicV1AutomationRunsRunIdRouteImport } from './routes/api/public/v1/automation.runs.$runId'
import { Route as ApiPublicV1WebhooksEndpointsEndpointIdTestRouteImport } from './routes/api/public/v1/webhooks.endpoints.$endpointId.test'
import { Route as ApiPublicV1AutomationPipelinesPipelineIdRunRouteImport } from './routes/api/public/v1/automation.pipelines.$pipelineId.run'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketplaceListingKeyRoute = MarketplaceListingKeyRouteImport.update({
  id: '/$listingKey',
  path: '/$listingKey',
  getParentRoute: () => MarketplaceRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsRoute = DashboardSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPoliciesRoute = DashboardPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMobileRoute = DashboardMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketplaceRoute = DashboardMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeveloperRoute = DashboardDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutomationRoute = DashboardAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutomationIndexRoute =
  DashboardAutomationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAutomationRoute,
  } as any)
const DashboardPoliciesRemoteInputRoute =
  DashboardPoliciesRemoteInputRouteImport.update({
    id: '/remote-input',
    path: '/remote-input',
    getParentRoute: () => DashboardPoliciesRoute,
  } as any)
const DashboardPoliciesFileTransferRoute =
  DashboardPoliciesFileTransferRouteImport.update({
    id: '/file-transfer',
    path: '/file-transfer',
    getParentRoute: () => DashboardPoliciesRoute,
  } as any)
const DashboardPoliciesClipboardRoute =
  DashboardPoliciesClipboardRouteImport.update({
    id: '/clipboard',
    path: '/clipboard',
    getParentRoute: () => DashboardPoliciesRoute,
  } as any)
const DashboardDevicesDeviceIdRoute =
  DashboardDevicesDeviceIdRouteImport.update({
    id: '/$deviceId',
    path: '/$deviceId',
    getParentRoute: () => DashboardDevicesRoute,
  } as any)
const DashboardAutomationTasksRoute =
  DashboardAutomationTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => DashboardAutomationRoute,
  } as any)
const DashboardAutomationSettingsRoute =
  DashboardAutomationSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardAutomationRoute,
  } as any)
const DashboardAutomationSchedulerRoute =
  DashboardAutomationSchedulerRouteImport.update({
    id: '/scheduler',
    path: '/scheduler',
    getParentRoute: () => DashboardAutomationRoute,
  } as any)
const DashboardAutomationRateLimitsRoute =
  DashboardAutomationRateLimitsRouteImport.update({
    id: '/rate-limits',
    path: '/rate-limits',
    getParentRoute: () => DashboardAutomationRoute,
  } as any)
const DashboardAutomationPipelinesRoute =
  DashboardAutomationPipelinesRouteImport.update({
    id: '/pipelines',
    path: '/pipelines',
    getParentRoute: () => DashboardAutomationRoute,
  } as any)
const DashboardAutomationLogsRoute = DashboardAutomationLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardAutomationRoute,
} as any)
const DashboardAutomationArtifactsRoute =
  DashboardAutomationArtifactsRouteImport.update({
    id: '/artifacts',
    path: '/artifacts',
    getParentRoute: () => DashboardAutomationRoute,
  } as any)
const DashboardAutomationAlertsRoute =
  DashboardAutomationAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => DashboardAutomationRoute,
  } as any)
const DashboardAutomationAccountsRoute =
  DashboardAutomationAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => DashboardAutomationRoute,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SessionsRoute = ApiPublicV1SessionsRouteImport.update({
  id: '/api/public/v1/sessions',
  path: '/api/public/v1/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1NotificationsRoute =
  ApiPublicV1NotificationsRouteImport.update({
    id: '/api/public/v1/notifications',
    path: '/api/public/v1/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1MeRoute = ApiPublicV1MeRouteImport.update({
  id: '/api/public/v1/me',
  path: '/api/public/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1DevicesRoute = ApiPublicV1DevicesRouteImport.update({
  id: '/api/public/v1/devices',
  path: '/api/public/v1/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1WebhooksEndpointsRoute =
  ApiPublicV1WebhooksEndpointsRouteImport.update({
    id: '/api/public/v1/webhooks/endpoints',
    path: '/api/public/v1/webhooks/endpoints',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1SupportTicketsRoute =
  ApiPublicV1SupportTicketsRouteImport.update({
    id: '/api/public/v1/support/tickets',
    path: '/api/public/v1/support/tickets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1SessionsSessionIdRoute =
  ApiPublicV1SessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => ApiPublicV1SessionsRoute,
  } as any)
const ApiPublicV1DevicesDeviceIdRoute =
  ApiPublicV1DevicesDeviceIdRouteImport.update({
    id: '/$deviceId',
    path: '/$deviceId',
    getParentRoute: () => ApiPublicV1DevicesRoute,
  } as any)
const ApiPublicV1BillingUsageRoute = ApiPublicV1BillingUsageRouteImport.update({
  id: '/api/public/v1/billing/usage',
  path: '/api/public/v1/billing/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AutomationPipelinesRoute =
  ApiPublicV1AutomationPipelinesRouteImport.update({
    id: '/api/public/v1/automation/pipelines',
    path: '/api/public/v1/automation/pipelines',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1AuditLogsRoute = ApiPublicV1AuditLogsRouteImport.update({
  id: '/api/public/v1/audit/logs',
  path: '/api/public/v1/audit/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1WebhooksEndpointsEndpointIdRoute =
  ApiPublicV1WebhooksEndpointsEndpointIdRouteImport.update({
    id: '/$endpointId',
    path: '/$endpointId',
    getParentRoute: () => ApiPublicV1WebhooksEndpointsRoute,
  } as any)
const ApiPublicV1SessionsSessionIdEndRoute =
  ApiPublicV1SessionsSessionIdEndRouteImport.update({
    id: '/end',
    path: '/end',
    getParentRoute: () => ApiPublicV1SessionsSessionIdRoute,
  } as any)
const ApiPublicV1DevicesDeviceIdPresenceRoute =
  ApiPublicV1DevicesDeviceIdPresenceRouteImport.update({
    id: '/presence',
    path: '/presence',
    getParentRoute: () => ApiPublicV1DevicesDeviceIdRoute,
  } as any)
const ApiPublicV1AutomationRunsRunIdRoute =
  ApiPublicV1AutomationRunsRunIdRouteImport.update({
    id: '/api/public/v1/automation/runs/$runId',
    path: '/api/public/v1/automation/runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1WebhooksEndpointsEndpointIdTestRoute =
  ApiPublicV1WebhooksEndpointsEndpointIdTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => ApiPublicV1WebhooksEndpointsEndpointIdRoute,
  } as any)
const ApiPublicV1AutomationPipelinesPipelineIdRunRoute =
  ApiPublicV1AutomationPipelinesPipelineIdRunRouteImport.update({
    id: '/$pipelineId/run',
    path: '/$pipelineId/run',
    getParentRoute: () => ApiPublicV1AutomationPipelinesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/automation': typeof DashboardAutomationRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/mobile': typeof DashboardMobileRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/policies': typeof DashboardPoliciesRouteWithChildren
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketplace/$listingKey': typeof MarketplaceListingKeyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/automation/accounts': typeof DashboardAutomationAccountsRoute
  '/dashboard/automation/alerts': typeof DashboardAutomationAlertsRoute
  '/dashboard/automation/artifacts': typeof DashboardAutomationArtifactsRoute
  '/dashboard/automation/logs': typeof DashboardAutomationLogsRoute
  '/dashboard/automation/pipelines': typeof DashboardAutomationPipelinesRoute
  '/dashboard/automation/rate-limits': typeof DashboardAutomationRateLimitsRoute
  '/dashboard/automation/scheduler': typeof DashboardAutomationSchedulerRoute
  '/dashboard/automation/settings': typeof DashboardAutomationSettingsRoute
  '/dashboard/automation/tasks': typeof DashboardAutomationTasksRoute
  '/dashboard/devices/$deviceId': typeof DashboardDevicesDeviceIdRoute
  '/dashboard/policies/clipboard': typeof DashboardPoliciesClipboardRoute
  '/dashboard/policies/file-transfer': typeof DashboardPoliciesFileTransferRoute
  '/dashboard/policies/remote-input': typeof DashboardPoliciesRemoteInputRoute
  '/dashboard/automation/': typeof DashboardAutomationIndexRoute
  '/api/public/v1/devices': typeof ApiPublicV1DevicesRouteWithChildren
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/notifications': typeof ApiPublicV1NotificationsRoute
  '/api/public/v1/sessions': typeof ApiPublicV1SessionsRouteWithChildren
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/v1/audit/logs': typeof ApiPublicV1AuditLogsRoute
  '/api/public/v1/automation/pipelines': typeof ApiPublicV1AutomationPipelinesRouteWithChildren
  '/api/public/v1/billing/usage': typeof ApiPublicV1BillingUsageRoute
  '/api/public/v1/devices/$deviceId': typeof ApiPublicV1DevicesDeviceIdRouteWithChildren
  '/api/public/v1/sessions/$sessionId': typeof ApiPublicV1SessionsSessionIdRouteWithChildren
  '/api/public/v1/support/tickets': typeof ApiPublicV1SupportTicketsRoute
  '/api/public/v1/webhooks/endpoints': typeof ApiPublicV1WebhooksEndpointsRouteWithChildren
  '/api/public/v1/automation/runs/$runId': typeof ApiPublicV1AutomationRunsRunIdRoute
  '/api/public/v1/devices/$deviceId/presence': typeof ApiPublicV1DevicesDeviceIdPresenceRoute
  '/api/public/v1/sessions/$sessionId/end': typeof ApiPublicV1SessionsSessionIdEndRoute
  '/api/public/v1/webhooks/endpoints/$endpointId': typeof ApiPublicV1WebhooksEndpointsEndpointIdRouteWithChildren
  '/api/public/v1/automation/pipelines/$pipelineId/run': typeof ApiPublicV1AutomationPipelinesPipelineIdRunRoute
  '/api/public/v1/webhooks/endpoints/$endpointId/test': typeof ApiPublicV1WebhooksEndpointsEndpointIdTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/mobile': typeof DashboardMobileRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/policies': typeof DashboardPoliciesRouteWithChildren
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketplace/$listingKey': typeof MarketplaceListingKeyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/automation/accounts': typeof DashboardAutomationAccountsRoute
  '/dashboard/automation/alerts': typeof DashboardAutomationAlertsRoute
  '/dashboard/automation/artifacts': typeof DashboardAutomationArtifactsRoute
  '/dashboard/automation/logs': typeof DashboardAutomationLogsRoute
  '/dashboard/automation/pipelines': typeof DashboardAutomationPipelinesRoute
  '/dashboard/automation/rate-limits': typeof DashboardAutomationRateLimitsRoute
  '/dashboard/automation/scheduler': typeof DashboardAutomationSchedulerRoute
  '/dashboard/automation/settings': typeof DashboardAutomationSettingsRoute
  '/dashboard/automation/tasks': typeof DashboardAutomationTasksRoute
  '/dashboard/devices/$deviceId': typeof DashboardDevicesDeviceIdRoute
  '/dashboard/policies/clipboard': typeof DashboardPoliciesClipboardRoute
  '/dashboard/policies/file-transfer': typeof DashboardPoliciesFileTransferRoute
  '/dashboard/policies/remote-input': typeof DashboardPoliciesRemoteInputRoute
  '/dashboard/automation': typeof DashboardAutomationIndexRoute
  '/api/public/v1/devices': typeof ApiPublicV1DevicesRouteWithChildren
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/notifications': typeof ApiPublicV1NotificationsRoute
  '/api/public/v1/sessions': typeof ApiPublicV1SessionsRouteWithChildren
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/v1/audit/logs': typeof ApiPublicV1AuditLogsRoute
  '/api/public/v1/automation/pipelines': typeof ApiPublicV1AutomationPipelinesRouteWithChildren
  '/api/public/v1/billing/usage': typeof ApiPublicV1BillingUsageRoute
  '/api/public/v1/devices/$deviceId': typeof ApiPublicV1DevicesDeviceIdRouteWithChildren
  '/api/public/v1/sessions/$sessionId': typeof ApiPublicV1SessionsSessionIdRouteWithChildren
  '/api/public/v1/support/tickets': typeof ApiPublicV1SupportTicketsRoute
  '/api/public/v1/webhooks/endpoints': typeof ApiPublicV1WebhooksEndpointsRouteWithChildren
  '/api/public/v1/automation/runs/$runId': typeof ApiPublicV1AutomationRunsRunIdRoute
  '/api/public/v1/devices/$deviceId/presence': typeof ApiPublicV1DevicesDeviceIdPresenceRoute
  '/api/public/v1/sessions/$sessionId/end': typeof ApiPublicV1SessionsSessionIdEndRoute
  '/api/public/v1/webhooks/endpoints/$endpointId': typeof ApiPublicV1WebhooksEndpointsEndpointIdRouteWithChildren
  '/api/public/v1/automation/pipelines/$pipelineId/run': typeof ApiPublicV1AutomationPipelinesPipelineIdRunRoute
  '/api/public/v1/webhooks/endpoints/$endpointId/test': typeof ApiPublicV1WebhooksEndpointsEndpointIdTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/automation': typeof DashboardAutomationRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/mobile': typeof DashboardMobileRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/policies': typeof DashboardPoliciesRouteWithChildren
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketplace/$listingKey': typeof MarketplaceListingKeyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/automation/accounts': typeof DashboardAutomationAccountsRoute
  '/dashboard/automation/alerts': typeof DashboardAutomationAlertsRoute
  '/dashboard/automation/artifacts': typeof DashboardAutomationArtifactsRoute
  '/dashboard/automation/logs': typeof DashboardAutomationLogsRoute
  '/dashboard/automation/pipelines': typeof DashboardAutomationPipelinesRoute
  '/dashboard/automation/rate-limits': typeof DashboardAutomationRateLimitsRoute
  '/dashboard/automation/scheduler': typeof DashboardAutomationSchedulerRoute
  '/dashboard/automation/settings': typeof DashboardAutomationSettingsRoute
  '/dashboard/automation/tasks': typeof DashboardAutomationTasksRoute
  '/dashboard/devices/$deviceId': typeof DashboardDevicesDeviceIdRoute
  '/dashboard/policies/clipboard': typeof DashboardPoliciesClipboardRoute
  '/dashboard/policies/file-transfer': typeof DashboardPoliciesFileTransferRoute
  '/dashboard/policies/remote-input': typeof DashboardPoliciesRemoteInputRoute
  '/dashboard/automation/': typeof DashboardAutomationIndexRoute
  '/api/public/v1/devices': typeof ApiPublicV1DevicesRouteWithChildren
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/notifications': typeof ApiPublicV1NotificationsRoute
  '/api/public/v1/sessions': typeof ApiPublicV1SessionsRouteWithChildren
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/v1/audit/logs': typeof ApiPublicV1AuditLogsRoute
  '/api/public/v1/automation/pipelines': typeof ApiPublicV1AutomationPipelinesRouteWithChildren
  '/api/public/v1/billing/usage': typeof ApiPublicV1BillingUsageRoute
  '/api/public/v1/devices/$deviceId': typeof ApiPublicV1DevicesDeviceIdRouteWithChildren
  '/api/public/v1/sessions/$sessionId': typeof ApiPublicV1SessionsSessionIdRouteWithChildren
  '/api/public/v1/support/tickets': typeof ApiPublicV1SupportTicketsRoute
  '/api/public/v1/webhooks/endpoints': typeof ApiPublicV1WebhooksEndpointsRouteWithChildren
  '/api/public/v1/automation/runs/$runId': typeof ApiPublicV1AutomationRunsRunIdRoute
  '/api/public/v1/devices/$deviceId/presence': typeof ApiPublicV1DevicesDeviceIdPresenceRoute
  '/api/public/v1/sessions/$sessionId/end': typeof ApiPublicV1SessionsSessionIdEndRoute
  '/api/public/v1/webhooks/endpoints/$endpointId': typeof ApiPublicV1WebhooksEndpointsEndpointIdRouteWithChildren
  '/api/public/v1/automation/pipelines/$pipelineId/run': typeof ApiPublicV1AutomationPipelinesPipelineIdRunRoute
  '/api/public/v1/webhooks/endpoints/$endpointId/test': typeof ApiPublicV1WebhooksEndpointsEndpointIdTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/audit'
    | '/dashboard/automation'
    | '/dashboard/billing'
    | '/dashboard/contacts'
    | '/dashboard/developer'
    | '/dashboard/devices'
    | '/dashboard/marketplace'
    | '/dashboard/mobile'
    | '/dashboard/notifications'
    | '/dashboard/policies'
    | '/dashboard/security'
    | '/dashboard/sessions'
    | '/dashboard/support'
    | '/dashboard/team'
    | '/invite/$token'
    | '/marketplace/$listingKey'
    | '/dashboard/'
    | '/dashboard/automation/accounts'
    | '/dashboard/automation/alerts'
    | '/dashboard/automation/artifacts'
    | '/dashboard/automation/logs'
    | '/dashboard/automation/pipelines'
    | '/dashboard/automation/rate-limits'
    | '/dashboard/automation/scheduler'
    | '/dashboard/automation/settings'
    | '/dashboard/automation/tasks'
    | '/dashboard/devices/$deviceId'
    | '/dashboard/policies/clipboard'
    | '/dashboard/policies/file-transfer'
    | '/dashboard/policies/remote-input'
    | '/dashboard/automation/'
    | '/api/public/v1/devices'
    | '/api/public/v1/me'
    | '/api/public/v1/notifications'
    | '/api/public/v1/sessions'
    | '/api/public/webhooks/stripe'
    | '/api/public/v1/audit/logs'
    | '/api/public/v1/automation/pipelines'
    | '/api/public/v1/billing/usage'
    | '/api/public/v1/devices/$deviceId'
    | '/api/public/v1/sessions/$sessionId'
    | '/api/public/v1/support/tickets'
    | '/api/public/v1/webhooks/endpoints'
    | '/api/public/v1/automation/runs/$runId'
    | '/api/public/v1/devices/$deviceId/presence'
    | '/api/public/v1/sessions/$sessionId/end'
    | '/api/public/v1/webhooks/endpoints/$endpointId'
    | '/api/public/v1/automation/pipelines/$pipelineId/run'
    | '/api/public/v1/webhooks/endpoints/$endpointId/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/audit'
    | '/dashboard/billing'
    | '/dashboard/contacts'
    | '/dashboard/developer'
    | '/dashboard/devices'
    | '/dashboard/marketplace'
    | '/dashboard/mobile'
    | '/dashboard/notifications'
    | '/dashboard/policies'
    | '/dashboard/security'
    | '/dashboard/sessions'
    | '/dashboard/support'
    | '/dashboard/team'
    | '/invite/$token'
    | '/marketplace/$listingKey'
    | '/dashboard'
    | '/dashboard/automation/accounts'
    | '/dashboard/automation/alerts'
    | '/dashboard/automation/artifacts'
    | '/dashboard/automation/logs'
    | '/dashboard/automation/pipelines'
    | '/dashboard/automation/rate-limits'
    | '/dashboard/automation/scheduler'
    | '/dashboard/automation/settings'
    | '/dashboard/automation/tasks'
    | '/dashboard/devices/$deviceId'
    | '/dashboard/policies/clipboard'
    | '/dashboard/policies/file-transfer'
    | '/dashboard/policies/remote-input'
    | '/dashboard/automation'
    | '/api/public/v1/devices'
    | '/api/public/v1/me'
    | '/api/public/v1/notifications'
    | '/api/public/v1/sessions'
    | '/api/public/webhooks/stripe'
    | '/api/public/v1/audit/logs'
    | '/api/public/v1/automation/pipelines'
    | '/api/public/v1/billing/usage'
    | '/api/public/v1/devices/$deviceId'
    | '/api/public/v1/sessions/$sessionId'
    | '/api/public/v1/support/tickets'
    | '/api/public/v1/webhooks/endpoints'
    | '/api/public/v1/automation/runs/$runId'
    | '/api/public/v1/devices/$deviceId/presence'
    | '/api/public/v1/sessions/$sessionId/end'
    | '/api/public/v1/webhooks/endpoints/$endpointId'
    | '/api/public/v1/automation/pipelines/$pipelineId/run'
    | '/api/public/v1/webhooks/endpoints/$endpointId/test'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/audit'
    | '/dashboard/automation'
    | '/dashboard/billing'
    | '/dashboard/contacts'
    | '/dashboard/developer'
    | '/dashboard/devices'
    | '/dashboard/marketplace'
    | '/dashboard/mobile'
    | '/dashboard/notifications'
    | '/dashboard/policies'
    | '/dashboard/security'
    | '/dashboard/sessions'
    | '/dashboard/support'
    | '/dashboard/team'
    | '/invite/$token'
    | '/marketplace/$listingKey'
    | '/dashboard/'
    | '/dashboard/automation/accounts'
    | '/dashboard/automation/alerts'
    | '/dashboard/automation/artifacts'
    | '/dashboard/automation/logs'
    | '/dashboard/automation/pipelines'
    | '/dashboard/automation/rate-limits'
    | '/dashboard/automation/scheduler'
    | '/dashboard/automation/settings'
    | '/dashboard/automation/tasks'
    | '/dashboard/devices/$deviceId'
    | '/dashboard/policies/clipboard'
    | '/dashboard/policies/file-transfer'
    | '/dashboard/policies/remote-input'
    | '/dashboard/automation/'
    | '/api/public/v1/devices'
    | '/api/public/v1/me'
    | '/api/public/v1/notifications'
    | '/api/public/v1/sessions'
    | '/api/public/webhooks/stripe'
    | '/api/public/v1/audit/logs'
    | '/api/public/v1/automation/pipelines'
    | '/api/public/v1/billing/usage'
    | '/api/public/v1/devices/$deviceId'
    | '/api/public/v1/sessions/$sessionId'
    | '/api/public/v1/support/tickets'
    | '/api/public/v1/webhooks/endpoints'
    | '/api/public/v1/automation/runs/$runId'
    | '/api/public/v1/devices/$deviceId/presence'
    | '/api/public/v1/sessions/$sessionId/end'
    | '/api/public/v1/webhooks/endpoints/$endpointId'
    | '/api/public/v1/automation/pipelines/$pipelineId/run'
    | '/api/public/v1/webhooks/endpoints/$endpointId/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicV1DevicesRoute: typeof ApiPublicV1DevicesRouteWithChildren
  ApiPublicV1MeRoute: typeof ApiPublicV1MeRoute
  ApiPublicV1NotificationsRoute: typeof ApiPublicV1NotificationsRoute
  ApiPublicV1SessionsRoute: typeof ApiPublicV1SessionsRouteWithChildren
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  ApiPublicV1AuditLogsRoute: typeof ApiPublicV1AuditLogsRoute
  ApiPublicV1AutomationPipelinesRoute: typeof ApiPublicV1AutomationPipelinesRouteWithChildren
  ApiPublicV1BillingUsageRoute: typeof ApiPublicV1BillingUsageRoute
  ApiPublicV1SupportTicketsRoute: typeof ApiPublicV1SupportTicketsRoute
  ApiPublicV1WebhooksEndpointsRoute: typeof ApiPublicV1WebhooksEndpointsRouteWithChildren
  ApiPublicV1AutomationRunsRunIdRoute: typeof ApiPublicV1AutomationRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/marketplace/$listingKey': {
      id: '/marketplace/$listingKey'
      path: '/$listingKey'
      fullPath: '/marketplace/$listingKey'
      preLoaderRoute: typeof MarketplaceListingKeyRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions': {
      id: '/dashboard/sessions'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof DashboardSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/policies': {
      id: '/dashboard/policies'
      path: '/policies'
      fullPath: '/dashboard/policies'
      preLoaderRoute: typeof DashboardPoliciesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mobile': {
      id: '/dashboard/mobile'
      path: '/mobile'
      fullPath: '/dashboard/mobile'
      preLoaderRoute: typeof DashboardMobileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketplace': {
      id: '/dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace'
      preLoaderRoute: typeof DashboardMarketplaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/devices': {
      id: '/dashboard/devices'
      path: '/devices'
      fullPath: '/dashboard/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/developer': {
      id: '/dashboard/developer'
      path: '/developer'
      fullPath: '/dashboard/developer'
      preLoaderRoute: typeof DashboardDeveloperRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts': {
      id: '/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/automation': {
      id: '/dashboard/automation'
      path: '/automation'
      fullPath: '/dashboard/automation'
      preLoaderRoute: typeof DashboardAutomationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/automation/': {
      id: '/dashboard/automation/'
      path: '/'
      fullPath: '/dashboard/automation/'
      preLoaderRoute: typeof DashboardAutomationIndexRouteImport
      parentRoute: typeof DashboardAutomationRoute
    }
    '/dashboard/policies/remote-input': {
      id: '/dashboard/policies/remote-input'
      path: '/remote-input'
      fullPath: '/dashboard/policies/remote-input'
      preLoaderRoute: typeof DashboardPoliciesRemoteInputRouteImport
      parentRoute: typeof DashboardPoliciesRoute
    }
    '/dashboard/policies/file-transfer': {
      id: '/dashboard/policies/file-transfer'
      path: '/file-transfer'
      fullPath: '/dashboard/policies/file-transfer'
      preLoaderRoute: typeof DashboardPoliciesFileTransferRouteImport
      parentRoute: typeof DashboardPoliciesRoute
    }
    '/dashboard/policies/clipboard': {
      id: '/dashboard/policies/clipboard'
      path: '/clipboard'
      fullPath: '/dashboard/policies/clipboard'
      preLoaderRoute: typeof DashboardPoliciesClipboardRouteImport
      parentRoute: typeof DashboardPoliciesRoute
    }
    '/dashboard/devices/$deviceId': {
      id: '/dashboard/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/dashboard/devices/$deviceId'
      preLoaderRoute: typeof DashboardDevicesDeviceIdRouteImport
      parentRoute: typeof DashboardDevicesRoute
    }
    '/dashboard/automation/tasks': {
      id: '/dashboard/automation/tasks'
      path: '/tasks'
      fullPath: '/dashboard/automation/tasks'
      preLoaderRoute: typeof DashboardAutomationTasksRouteImport
      parentRoute: typeof DashboardAutomationRoute
    }
    '/dashboard/automation/settings': {
      id: '/dashboard/automation/settings'
      path: '/settings'
      fullPath: '/dashboard/automation/settings'
      preLoaderRoute: typeof DashboardAutomationSettingsRouteImport
      parentRoute: typeof DashboardAutomationRoute
    }
    '/dashboard/automation/scheduler': {
      id: '/dashboard/automation/scheduler'
      path: '/scheduler'
      fullPath: '/dashboard/automation/scheduler'
      preLoaderRoute: typeof DashboardAutomationSchedulerRouteImport
      parentRoute: typeof DashboardAutomationRoute
    }
    '/dashboard/automation/rate-limits': {
      id: '/dashboard/automation/rate-limits'
      path: '/rate-limits'
      fullPath: '/dashboard/automation/rate-limits'
      preLoaderRoute: typeof DashboardAutomationRateLimitsRouteImport
      parentRoute: typeof DashboardAutomationRoute
    }
    '/dashboard/automation/pipelines': {
      id: '/dashboard/automation/pipelines'
      path: '/pipelines'
      fullPath: '/dashboard/automation/pipelines'
      preLoaderRoute: typeof DashboardAutomationPipelinesRouteImport
      parentRoute: typeof DashboardAutomationRoute
    }
    '/dashboard/automation/logs': {
      id: '/dashboard/automation/logs'
      path: '/logs'
      fullPath: '/dashboard/automation/logs'
      preLoaderRoute: typeof DashboardAutomationLogsRouteImport
      parentRoute: typeof DashboardAutomationRoute
    }
    '/dashboard/automation/artifacts': {
      id: '/dashboard/automation/artifacts'
      path: '/artifacts'
      fullPath: '/dashboard/automation/artifacts'
      preLoaderRoute: typeof DashboardAutomationArtifactsRouteImport
      parentRoute: typeof DashboardAutomationRoute
    }
    '/dashboard/automation/alerts': {
      id: '/dashboard/automation/alerts'
      path: '/alerts'
      fullPath: '/dashboard/automation/alerts'
      preLoaderRoute: typeof DashboardAutomationAlertsRouteImport
      parentRoute: typeof DashboardAutomationRoute
    }
    '/dashboard/automation/accounts': {
      id: '/dashboard/automation/accounts'
      path: '/accounts'
      fullPath: '/dashboard/automation/accounts'
      preLoaderRoute: typeof DashboardAutomationAccountsRouteImport
      parentRoute: typeof DashboardAutomationRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/sessions': {
      id: '/api/public/v1/sessions'
      path: '/api/public/v1/sessions'
      fullPath: '/api/public/v1/sessions'
      preLoaderRoute: typeof ApiPublicV1SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/notifications': {
      id: '/api/public/v1/notifications'
      path: '/api/public/v1/notifications'
      fullPath: '/api/public/v1/notifications'
      preLoaderRoute: typeof ApiPublicV1NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/me': {
      id: '/api/public/v1/me'
      path: '/api/public/v1/me'
      fullPath: '/api/public/v1/me'
      preLoaderRoute: typeof ApiPublicV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/devices': {
      id: '/api/public/v1/devices'
      path: '/api/public/v1/devices'
      fullPath: '/api/public/v1/devices'
      preLoaderRoute: typeof ApiPublicV1DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/webhooks/endpoints': {
      id: '/api/public/v1/webhooks/endpoints'
      path: '/api/public/v1/webhooks/endpoints'
      fullPath: '/api/public/v1/webhooks/endpoints'
      preLoaderRoute: typeof ApiPublicV1WebhooksEndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/support/tickets': {
      id: '/api/public/v1/support/tickets'
      path: '/api/public/v1/support/tickets'
      fullPath: '/api/public/v1/support/tickets'
      preLoaderRoute: typeof ApiPublicV1SupportTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/sessions/$sessionId': {
      id: '/api/public/v1/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/public/v1/sessions/$sessionId'
      preLoaderRoute: typeof ApiPublicV1SessionsSessionIdRouteImport
      parentRoute: typeof ApiPublicV1SessionsRoute
    }
    '/api/public/v1/devices/$deviceId': {
      id: '/api/public/v1/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/api/public/v1/devices/$deviceId'
      preLoaderRoute: typeof ApiPublicV1DevicesDeviceIdRouteImport
      parentRoute: typeof ApiPublicV1DevicesRoute
    }
    '/api/public/v1/billing/usage': {
      id: '/api/public/v1/billing/usage'
      path: '/api/public/v1/billing/usage'
      fullPath: '/api/public/v1/billing/usage'
      preLoaderRoute: typeof ApiPublicV1BillingUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/automation/pipelines': {
      id: '/api/public/v1/automation/pipelines'
      path: '/api/public/v1/automation/pipelines'
      fullPath: '/api/public/v1/automation/pipelines'
      preLoaderRoute: typeof ApiPublicV1AutomationPipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/audit/logs': {
      id: '/api/public/v1/audit/logs'
      path: '/api/public/v1/audit/logs'
      fullPath: '/api/public/v1/audit/logs'
      preLoaderRoute: typeof ApiPublicV1AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/webhooks/endpoints/$endpointId': {
      id: '/api/public/v1/webhooks/endpoints/$endpointId'
      path: '/$endpointId'
      fullPath: '/api/public/v1/webhooks/endpoints/$endpointId'
      preLoaderRoute: typeof ApiPublicV1WebhooksEndpointsEndpointIdRouteImport
      parentRoute: typeof ApiPublicV1WebhooksEndpointsRoute
    }
    '/api/public/v1/sessions/$sessionId/end': {
      id: '/api/public/v1/sessions/$sessionId/end'
      path: '/end'
      fullPath: '/api/public/v1/sessions/$sessionId/end'
      preLoaderRoute: typeof ApiPublicV1SessionsSessionIdEndRouteImport
      parentRoute: typeof ApiPublicV1SessionsSessionIdRoute
    }
    '/api/public/v1/devices/$deviceId/presence': {
      id: '/api/public/v1/devices/$deviceId/presence'
      path: '/presence'
      fullPath: '/api/public/v1/devices/$deviceId/presence'
      preLoaderRoute: typeof ApiPublicV1DevicesDeviceIdPresenceRouteImport
      parentRoute: typeof ApiPublicV1DevicesDeviceIdRoute
    }
    '/api/public/v1/automation/runs/$runId': {
      id: '/api/public/v1/automation/runs/$runId'
      path: '/api/public/v1/automation/runs/$runId'
      fullPath: '/api/public/v1/automation/runs/$runId'
      preLoaderRoute: typeof ApiPublicV1AutomationRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/webhooks/endpoints/$endpointId/test': {
      id: '/api/public/v1/webhooks/endpoints/$endpointId/test'
      path: '/test'
      fullPath: '/api/public/v1/webhooks/endpoints/$endpointId/test'
      preLoaderRoute: typeof ApiPublicV1WebhooksEndpointsEndpointIdTestRouteImport
      parentRoute: typeof ApiPublicV1WebhooksEndpointsEndpointIdRoute
    }
    '/api/public/v1/automation/pipelines/$pipelineId/run': {
      id: '/api/public/v1/automation/pipelines/$pipelineId/run'
      path: '/$pipelineId/run'
      fullPath: '/api/public/v1/automation/pipelines/$pipelineId/run'
      preLoaderRoute: typeof ApiPublicV1AutomationPipelinesPipelineIdRunRouteImport
      parentRoute: typeof ApiPublicV1AutomationPipelinesRoute
    }
  }
}

interface DashboardAutomationRouteChildren {
  DashboardAutomationAccountsRoute: typeof DashboardAutomationAccountsRoute
  DashboardAutomationAlertsRoute: typeof DashboardAutomationAlertsRoute
  DashboardAutomationArtifactsRoute: typeof DashboardAutomationArtifactsRoute
  DashboardAutomationLogsRoute: typeof DashboardAutomationLogsRoute
  DashboardAutomationPipelinesRoute: typeof DashboardAutomationPipelinesRoute
  DashboardAutomationRateLimitsRoute: typeof DashboardAutomationRateLimitsRoute
  DashboardAutomationSchedulerRoute: typeof DashboardAutomationSchedulerRoute
  DashboardAutomationSettingsRoute: typeof DashboardAutomationSettingsRoute
  DashboardAutomationTasksRoute: typeof DashboardAutomationTasksRoute
  DashboardAutomationIndexRoute: typeof DashboardAutomationIndexRoute
}

const DashboardAutomationRouteChildren: DashboardAutomationRouteChildren = {
  DashboardAutomationAccountsRoute: DashboardAutomationAccountsRoute,
  DashboardAutomationAlertsRoute: DashboardAutomationAlertsRoute,
  DashboardAutomationArtifactsRoute: DashboardAutomationArtifactsRoute,
  DashboardAutomationLogsRoute: DashboardAutomationLogsRoute,
  DashboardAutomationPipelinesRoute: DashboardAutomationPipelinesRoute,
  DashboardAutomationRateLimitsRoute: DashboardAutomationRateLimitsRoute,
  DashboardAutomationSchedulerRoute: DashboardAutomationSchedulerRoute,
  DashboardAutomationSettingsRoute: DashboardAutomationSettingsRoute,
  DashboardAutomationTasksRoute: DashboardAutomationTasksRoute,
  DashboardAutomationIndexRoute: DashboardAutomationIndexRoute,
}

const DashboardAutomationRouteWithChildren =
  DashboardAutomationRoute._addFileChildren(DashboardAutomationRouteChildren)

interface DashboardDevicesRouteChildren {
  DashboardDevicesDeviceIdRoute: typeof DashboardDevicesDeviceIdRoute
}

const DashboardDevicesRouteChildren: DashboardDevicesRouteChildren = {
  DashboardDevicesDeviceIdRoute: DashboardDevicesDeviceIdRoute,
}

const DashboardDevicesRouteWithChildren =
  DashboardDevicesRoute._addFileChildren(DashboardDevicesRouteChildren)

interface DashboardPoliciesRouteChildren {
  DashboardPoliciesClipboardRoute: typeof DashboardPoliciesClipboardRoute
  DashboardPoliciesFileTransferRoute: typeof DashboardPoliciesFileTransferRoute
  DashboardPoliciesRemoteInputRoute: typeof DashboardPoliciesRemoteInputRoute
}

const DashboardPoliciesRouteChildren: DashboardPoliciesRouteChildren = {
  DashboardPoliciesClipboardRoute: DashboardPoliciesClipboardRoute,
  DashboardPoliciesFileTransferRoute: DashboardPoliciesFileTransferRoute,
  DashboardPoliciesRemoteInputRoute: DashboardPoliciesRemoteInputRoute,
}

const DashboardPoliciesRouteWithChildren =
  DashboardPoliciesRoute._addFileChildren(DashboardPoliciesRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardAutomationRoute: typeof DashboardAutomationRouteWithChildren
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardDeveloperRoute: typeof DashboardDeveloperRoute
  DashboardDevicesRoute: typeof DashboardDevicesRouteWithChildren
  DashboardMarketplaceRoute: typeof DashboardMarketplaceRoute
  DashboardMobileRoute: typeof DashboardMobileRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPoliciesRoute: typeof DashboardPoliciesRouteWithChildren
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSessionsRoute: typeof DashboardSessionsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardAutomationRoute: DashboardAutomationRouteWithChildren,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardDeveloperRoute: DashboardDeveloperRoute,
  DashboardDevicesRoute: DashboardDevicesRouteWithChildren,
  DashboardMarketplaceRoute: DashboardMarketplaceRoute,
  DashboardMobileRoute: DashboardMobileRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPoliciesRoute: DashboardPoliciesRouteWithChildren,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSessionsRoute: DashboardSessionsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceListingKeyRoute: typeof MarketplaceListingKeyRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceListingKeyRoute: MarketplaceListingKeyRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface ApiPublicV1DevicesDeviceIdRouteChildren {
  ApiPublicV1DevicesDeviceIdPresenceRoute: typeof ApiPublicV1DevicesDeviceIdPresenceRoute
}

const ApiPublicV1DevicesDeviceIdRouteChildren: ApiPublicV1DevicesDeviceIdRouteChildren =
  {
    ApiPublicV1DevicesDeviceIdPresenceRoute:
      ApiPublicV1DevicesDeviceIdPresenceRoute,
  }

const ApiPublicV1DevicesDeviceIdRouteWithChildren =
  ApiPublicV1DevicesDeviceIdRoute._addFileChildren(
    ApiPublicV1DevicesDeviceIdRouteChildren,
  )

interface ApiPublicV1DevicesRouteChildren {
  ApiPublicV1DevicesDeviceIdRoute: typeof ApiPublicV1DevicesDeviceIdRouteWithChildren
}

const ApiPublicV1DevicesRouteChildren: ApiPublicV1DevicesRouteChildren = {
  ApiPublicV1DevicesDeviceIdRoute: ApiPublicV1DevicesDeviceIdRouteWithChildren,
}

const ApiPublicV1DevicesRouteWithChildren =
  ApiPublicV1DevicesRoute._addFileChildren(ApiPublicV1DevicesRouteChildren)

interface ApiPublicV1SessionsSessionIdRouteChildren {
  ApiPublicV1SessionsSessionIdEndRoute: typeof ApiPublicV1SessionsSessionIdEndRoute
}

const ApiPublicV1SessionsSessionIdRouteChildren: ApiPublicV1SessionsSessionIdRouteChildren =
  {
    ApiPublicV1SessionsSessionIdEndRoute: ApiPublicV1SessionsSessionIdEndRoute,
  }

const ApiPublicV1SessionsSessionIdRouteWithChildren =
  ApiPublicV1SessionsSessionIdRoute._addFileChildren(
    ApiPublicV1SessionsSessionIdRouteChildren,
  )

interface ApiPublicV1SessionsRouteChildren {
  ApiPublicV1SessionsSessionIdRoute: typeof ApiPublicV1SessionsSessionIdRouteWithChildren
}

const ApiPublicV1SessionsRouteChildren: ApiPublicV1SessionsRouteChildren = {
  ApiPublicV1SessionsSessionIdRoute:
    ApiPublicV1SessionsSessionIdRouteWithChildren,
}

const ApiPublicV1SessionsRouteWithChildren =
  ApiPublicV1SessionsRoute._addFileChildren(ApiPublicV1SessionsRouteChildren)

interface ApiPublicV1AutomationPipelinesRouteChildren {
  ApiPublicV1AutomationPipelinesPipelineIdRunRoute: typeof ApiPublicV1AutomationPipelinesPipelineIdRunRoute
}

const ApiPublicV1AutomationPipelinesRouteChildren: ApiPublicV1AutomationPipelinesRouteChildren =
  {
    ApiPublicV1AutomationPipelinesPipelineIdRunRoute:
      ApiPublicV1AutomationPipelinesPipelineIdRunRoute,
  }

const ApiPublicV1AutomationPipelinesRouteWithChildren =
  ApiPublicV1AutomationPipelinesRoute._addFileChildren(
    ApiPublicV1AutomationPipelinesRouteChildren,
  )

interface ApiPublicV1WebhooksEndpointsEndpointIdRouteChildren {
  ApiPublicV1WebhooksEndpointsEndpointIdTestRoute: typeof ApiPublicV1WebhooksEndpointsEndpointIdTestRoute
}

const ApiPublicV1WebhooksEndpointsEndpointIdRouteChildren: ApiPublicV1WebhooksEndpointsEndpointIdRouteChildren =
  {
    ApiPublicV1WebhooksEndpointsEndpointIdTestRoute:
      ApiPublicV1WebhooksEndpointsEndpointIdTestRoute,
  }

const ApiPublicV1WebhooksEndpointsEndpointIdRouteWithChildren =
  ApiPublicV1WebhooksEndpointsEndpointIdRoute._addFileChildren(
    ApiPublicV1WebhooksEndpointsEndpointIdRouteChildren,
  )

interface ApiPublicV1WebhooksEndpointsRouteChildren {
  ApiPublicV1WebhooksEndpointsEndpointIdRoute: typeof ApiPublicV1WebhooksEndpointsEndpointIdRouteWithChildren
}

const ApiPublicV1WebhooksEndpointsRouteChildren: ApiPublicV1WebhooksEndpointsRouteChildren =
  {
    ApiPublicV1WebhooksEndpointsEndpointIdRoute:
      ApiPublicV1WebhooksEndpointsEndpointIdRouteWithChildren,
  }

const ApiPublicV1WebhooksEndpointsRouteWithChildren =
  ApiPublicV1WebhooksEndpointsRoute._addFileChildren(
    ApiPublicV1WebhooksEndpointsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicV1DevicesRoute: ApiPublicV1DevicesRouteWithChildren,
  ApiPublicV1MeRoute: ApiPublicV1MeRoute,
  ApiPublicV1NotificationsRoute: ApiPublicV1NotificationsRoute,
  ApiPublicV1SessionsRoute: ApiPublicV1SessionsRouteWithChildren,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  ApiPublicV1AuditLogsRoute: ApiPublicV1AuditLogsRoute,
  ApiPublicV1AutomationPipelinesRoute:
    ApiPublicV1AutomationPipelinesRouteWithChildren,
  ApiPublicV1BillingUsageRoute: ApiPublicV1BillingUsageRoute,
  ApiPublicV1SupportTicketsRoute: ApiPublicV1SupportTicketsRoute,
  ApiPublicV1WebhooksEndpointsRoute:
    ApiPublicV1WebhooksEndpointsRouteWithChildren,
  ApiPublicV1AutomationRunsRunIdRoute: ApiPublicV1AutomationRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
